name: publish
on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
   publish-hello-docker-image:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
   - name: Login to GitHub Container Registry
     uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
     with:
       registry: ${{ env.REGISTRY }}
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
   - name: Build the hello-docker Docker image
     run: |
         docker build . --tag ghcr.io/joakimeriksson/hello-docker-gcr-demo:latest
         docker run ghcr.io/joakimeriksson/hello-docker-gcr-demo:latest
         docker push ghcr.io/joakimeriksson/hello-docker-gcr-demo:latest